import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./context/theme-provider";
import ThemeToggle from "./components/ThemeToggle";
import NavBar from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <header className="flex items-center justify-between bg-gray-300 px-20 py-4 text-black dark:bg-gray-700 dark:text-white">
            <h1>Aqif Bashah</h1>
            <NavBar />
            <ThemeToggle />
          </header>
          <main className="px-20">{children}</main>
          <footer className="mt-4 bg-gray-200 p-4 text-black dark:bg-gray-800 dark:text-white">
            © 2025 My Portfolio
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
