import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./context/theme-provider";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Aqif Bashah Port",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-saira antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <main>{children}</main>
          {/* <footer className="bg-gray-200 p-4 text-black dark:bg-gray-800 dark:text-white">
            © 2025 My Portfolio
          </footer> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
